/**
 * TS ↔ Python parity for the L1 pack (ticket F4).
 *
 * The server's ingress guard is only an independent check for as long as it agrees
 * with the client. Two implementations of one rule set drift unless something forces
 * them not to — and ours drifted on day one, when the mock server's pack was missing
 * PHONE_IN, GSTIN and IFSC that the client caught.
 *
 * The corpus and the Python verdicts are generated by `server/tests/test_parity.py`.
 * This asserts the TypeScript pack reaches the same conclusion on every case. Neither
 * side owns the expected answers; they must simply agree.
 *
 * When this fails, fix the pack that is WRONG — do not edit the fixture. The fixture
 * is the disagreement, not the bug.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { containsPii, scanText } from '../src/detectors/l1-regex/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const FIXTURE = resolve(here, '../../eval/fixtures/parity-corpus.json');

interface Case {
  text: string;
  contains_pii: boolean;
  classes: string[];
}

interface Corpus {
  note: string;
  count: number;
  cases: Case[];
}

const corpus = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Corpus;

describe('the two PII packs agree', () => {
  it('has a corpus large enough to catch drift', () => {
    expect(corpus.cases.length).toBeGreaterThan(800);
  });

  it('agrees on whether each string contains PII — zero disagreements', () => {
    const disagreements: { text: string; ts: boolean; py: boolean }[] = [];

    for (const c of corpus.cases) {
      const ts = containsPii(c.text);
      if (ts !== c.contains_pii) {
        disagreements.push({ text: c.text, ts, py: c.contains_pii });
      }
    }

    // Report the first few so the failure is diagnosable without a debugger.
    expect(
      disagreements.slice(0, 5),
      String(disagreements.length) + ' of ' + String(corpus.cases.length) + ' disagreed',
    ).toEqual([]);
  });

  it('agrees on which classes were found', () => {
    const disagreements: { text: string; ts: string[]; py: string[] }[] = [];

    for (const c of corpus.cases) {
      const ts = [...new Set(scanText(c.text).map((m) => m.cls))].sort();
      const py = [...c.classes].sort();
      if (ts.join(',') !== py.join(',')) {
        disagreements.push({ text: c.text, ts, py });
      }
    }

    expect(
      disagreements.slice(0, 5),
      String(disagreements.length) + ' of ' + String(corpus.cases.length) + ' disagreed',
    ).toEqual([]);
  });

  it('the corpus actually exercises both outcomes', () => {
    // A corpus where everything is PII, or nothing is, would pass while proving
    // nothing about either implementation.
    const positives = corpus.cases.filter((c) => c.contains_pii).length;
    const ratio = positives / corpus.cases.length;
    expect(ratio).toBeGreaterThan(0.2);
    expect(ratio).toBeLessThan(0.95);
  });
});
