# generated by datamodel-codegen:
#   filename:  action-plan-v1.json
#   timestamp: 2026-09-05T19:32:00+00:00
# pyright: reportInvalidTypeForm=false

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class Expect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page_change: bool | None = None
    assert_role: constr(max_length=32) | None = None
    assert_text_absent: constr(max_length=128) | None = None


class NextTierHint(Enum):
    int_0 = 0
    int_1 = 1
    int_2 = 2


class Risk(Enum):
    safe = 'safe'
    medium = 'medium'
    high = 'high'


class Target1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    point: list[float] = Field(..., max_length=2, min_length=2)


class Target(RootModel[constr(pattern=r'^e[0-9]{1,4}$') | Target1]):
    root: constr(pattern=r'^e[0-9]{1,4}$') | Target1


class Action1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['click']
    target: Target
    risk: Risk | None = None
    reason: constr(max_length=200) | None = None


class Action2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['type']
    target: Target
    value: constr(max_length=256) | None = None
    value_ref: constr(pattern=r'^⟦[A-Z][A-Z0-9_]*_[0-9]+⟧$') | None = None
    clear_first: bool | None = None
    risk: Risk | None = None


class Action3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['select']
    target: Target
    option: constr(max_length=128)
    risk: Risk | None = None


class Direction(Enum):
    up = 'up'
    down = 'down'
    left = 'left'
    right = 'right'
    to_element = 'to_element'


class Action4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['scroll']
    direction: Direction
    amount: int | None = None
    target: Target | None = None
    risk: Risk | None = None


class Action5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['key']
    combo: constr(max_length=32)
    risk: Risk | None = None


class Action6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['navigate']
    url: constr(max_length=2048)
    risk: Literal['high'] | None = None


class Action7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['wait']
    ms: conint(ge=0, le=5000) | None = None


class FieldModel(RootModel[constr(max_length=64)]):
    root: constr(max_length=64)


class Action8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['extract']
    targets: list[Target] = Field(..., max_length=20)
    fields: list[FieldModel] | None = Field(None, max_length=20)


class Option(RootModel[constr(max_length=64)]):
    root: constr(max_length=64)


class Action9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['ask_user']
    question: constr(max_length=300)
    options: list[Option] | None = Field(None, max_length=6)


class Action10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['done']
    summary: constr(max_length=800) | None = None


class Action11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['fail']
    reason: constr(max_length=300) | None = None


class Action(
    RootModel[
        Action1
        | Action2
        | Action3
        | Action4
        | Action5
        | Action6
        | Action7
        | Action8
        | Action9
        | Action10
        | Action11
    ]
):
    root: (
        Action1
        | Action2
        | Action3
        | Action4
        | Action5
        | Action6
        | Action7
        | Action8
        | Action9
        | Action10
        | Action11
    )


class ActionPlan(BaseModel):

    model_config = ConfigDict(
        extra='forbid',
    )

    plan_id: constr(max_length=32)
    trace_id: constr(pattern=r'^t_[0-9]{1,6}$')

    reasoning: constr(max_length=800) | None = None
    response: constr(max_length=2000) | None = None

    actions: list[Action] = Field(..., max_length=3)

    expect: Expect | None = None
    next_tier_hint: NextTierHint | None = None
    need_visual: bool | None = None

    done: bool

    confidence: confloat(ge=0.0, le=1.0) | None = None
    