# generated by datamodel-codegen:
#   filename:  ssg-v1.json
#   timestamp: 2026-09-05T19:31:50+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class Tier(Enum):
    int_0 = 0
    int_1 = 1
    int_2 = 2


class Methods(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    placeholder: conint(ge=0) | None = None
    blackout: conint(ge=0) | None = None
    blur: conint(ge=0) | None = None
    pixelate: conint(ge=0) | None = None
    drop: conint(ge=0) | None = None


class Detector(RootModel[constr(max_length=64)]):
    root: constr(max_length=64)


class RedactionManifestV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    policy_id: constr(max_length=64)
    counts: dict[constr(pattern=r'^[A-Z][A-Z0-9_]{0,31}$'), conint(ge=0)]
    methods: Methods
    detectors: list[Detector] = Field(..., max_length=24)
    coverage_confidence: confloat(ge=0.0, le=1.0)
    unexplained_pixel_ratio: confloat(ge=0.0, le=1.0) | None = None
    marker_convention: constr(max_length=128) | None = None


class SafeText(RootModel[constr(max_length=2048)]):
    root: constr(max_length=2048) = Field(
        ...,
        description='Text that has passed redaction. May contain U+27E6 CLASS_N U+27E7 tokens.',
    )


class Bbox(RootModel[list[float]]):
    root: list[float] = Field(..., max_length=4, min_length=4)


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    w: conint(ge=0)
    h: conint(ge=0)
    dpr: confloat(ge=0.0)
    scroll_y: int
    doc_h: conint(ge=0) | None = None


class PageType(Enum):
    form = 'form'
    article = 'article'
    list = 'list'
    canvas_app = 'canvas_app'
    media = 'media'
    pdf = 'pdf'
    chat = 'chat'
    dashboard = 'dashboard'
    unknown = 'unknown'


class Sensitivity(Enum):
    public = 'public'
    semi_private = 'semi_private'
    private = 'private'
    credential = 'credential'


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    origin_class: constr(max_length=64)
    path_shape: constr(max_length=128) | None = None
    title: SafeText | None = None
    lang: constr(max_length=12) | None = None
    page_type: PageType
    sensitivity: Sensitivity


class Method(Enum):
    placeholder = 'placeholder'
    blackout = 'blackout'
    blur = 'blur'
    pixelate = 'pixelate'
    drop = 'drop'


class Redaction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applied: bool
    class_: constr(max_length=32) | None = Field(None, alias='class')
    method: Method | None = None


class ActionableEnum(Enum):
    click = 'click'
    type = 'type'
    select = 'select'
    clear = 'clear'
    hover = 'hover'
    focus = 'focus'
    scroll = 'scroll'


class ClientRisk(Enum):
    safe = 'safe'
    medium = 'medium'
    high = 'high'


class Element(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^e[0-9]{1,4}$')
    role: constr(max_length=32)
    tag: constr(max_length=16) | None = None
    input_type: constr(max_length=24) | None = None
    bbox: Bbox
    z: int | None = None
    visible: bool | None = None
    name: SafeText | None = None
    value: SafeText | None = None
    placeholder: SafeText | None = None
    state: dict[str, bool] | None = None
    redaction: Redaction | None = None
    actionable: list[ActionableEnum] = Field(..., max_length=8)
    client_risk: ClientRisk | None = None
    risk_reason: constr(max_length=128) | None = None


class Source(Enum):
    dom = 'dom'
    ocr = 'ocr'


class TextBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^t[0-9]{1,4}$')
    bbox: Bbox
    source: Source
    text: SafeText
    ocr_conf: confloat(ge=0.0, le=1.0) | None = None


class Kind(Enum):
    img = 'img'
    video = 'video'
    canvas = 'canvas'
    iframe = 'iframe'
    svg = 'svg'
    unknown = 'unknown'


class VisualRegion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^v[0-9]{1,4}$')
    bbox: Bbox
    kind: Kind
    caption: SafeText | None = None
    redaction: Redaction | None = None


class Outcome(Enum):
    advanced = 'advanced'
    no_change = 'no_change'
    error = 'error'
    blocked = 'blocked'


class HistoryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: conint(ge=0)
    action: constr(max_length=32)
    target: constr(max_length=16) | None = None
    outcome: Outcome


class Screenshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    format: Literal['jpeg']
    w: int
    h: int
    q: conint(ge=1, le=100) | None = None
    sha256: constr(pattern=r'^[0-9a-f]{64}$')
    redacted: Literal[True]


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    screenshot: Screenshot


class SanitizedScreenGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ssg_version: Literal['1.0']
    session_id: constr(pattern=r'^eph_[0-9a-f]{8,32}$')
    trace_id: constr(pattern=r'^t_[0-9]{1,6}$')
    step: conint(ge=0, le=200)
    tier: Tier
    purpose: constr(max_length=64)
    goal: SafeText
    viewport: Viewport
    page: Page
    elements: list[Element] = Field(..., max_length=400)
    text_blocks: list[TextBlock] | None = Field(None, max_length=200)
    visual_regions: list[VisualRegion] | None = Field(None, max_length=100)
    history: list[HistoryItem] | None = Field(None, max_length=20)
    redaction_manifest: RedactionManifestV1
    attachment: Attachment | None = None
